<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\AFH.Common.Errors\AFH.Common.Errors.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Core" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>AFH.Common.Errors.AzureFunctions</AssemblyName>
    <PackageId>AFH.Common.Errors.AzureFunctions</PackageId>
    <Description>Azure Functions adapter for the AFH common error SDK.</Description>
  </PropertyGroup>
</Project>
