<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\AFH.Errors.EntityFramework\AFH.Errors.EntityFramework.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>AFH.Errors.EntityFramework.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <Description>Placeholder test project for AFH.Errors.EntityFramework.</Description>
  </PropertyGroup>
</Project>
